[package]
name = "enigma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-integer = {version = "0.5.3", features = ["macro"]}
itertools = "0.10.3"
strum = "0.24.1"
